feat: add server and channel schema
SuperAayush/TWTCORD pull request #17
Opened 2022-04-18 18:52 UTC by AayushShuk1a

Added Server and Channel Schema with following details:-

Server Details
-Server Name
-Server Profile
-Server Members
-Server TextChannels
-Server Owners
-Server VoiceChannels

Channel Details
-channelName
-newMessage
ServerName

Closes #15

2022-04-18 18:56 UTC, chandankumar1307 requested changes
Get it done ASAP

2022-04-18 18:56 UTC, chandankumar1307 commented on server/Routes/Routes.js
> +Router.get("/createserver", createServer);
Created Post request but using get. Fix this

2022-04-18 19:03 UTC, chandankumar1307 approved these changes
Looks Good

2022-04-18 19:11 UTC, SuperAayush approved these changes
LGTM

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-04-19 16:04 UTC, bhavyastar approved these changes
LGTM

2022-04-19 16:20 UTC, chirag0002 approved these changes
LGTM

2022-04-19 16:22 UTC, merged